// article
export const ARTICLE_SET_KEYWORD = 'ARTICLE_SET_KEYWORD';
export const ARTICLE_GET_TAG_LIST = 'ARTICLE_GET_TAG_LIST';
export const ARTICLE_GET_ARTICLE_LIST_BY_VIEW_COUNT_DESC = 'ARTICLE_GET_ARTICLE_LIST_BY_VIEW_COUNT_DESC';